# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: nasa-hunch-postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    ports:
      - '5432:5432'
  storage:
    container_name: hunch.docker.test
    image: zenko/cloudserver
    volumes:
      - ./cloudServerConfig.json:/usr/src/app/config.json
    ports:
      - '8000:8000'
    environment:
      - REMOTE_MANAGEMENT_DISABLE=1
      - S3BACKEND=mem
    command: bash -c "yarn start"
  web:
    image: node:20.9.0-alpine3.18
    container_name: nasa-hunch-web
    environment:
      - ORIGIN=http://localhost:3000
      - CODESPACES
    ports:
      - '3000:3000'
    env_file:
      - .env.test
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/.pnpm-store/
    working_dir: /app
    command: sh -c "npm i -g pnpm@8.12.1 && pnpm install && pnpm run db:deploy && pnpm run s3devdata && pnpm run seed && pnpm run dev --host"
    depends_on:
      - db
      - storage
