# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    container_name: nasa-hunch-postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  storage:
    container_name: s3.docker.hunch
    image: zenko/cloudserver
    ports:
      - '8000:8000'
    environment:
      - REMOTE_MANAGEMENT_DISABLE=1
      - S3BACKEND=mem
    command: bash -c "yarn start"
  web:
    image: node:20.9.0-alpine3.18
    container_name: nasa-hunch-web
    environment:
      - OUTER_PORT_FRONTEND=3000
      - INNER_PORT_FRONTEND=5173
      - CODESPACES
    ports:
      - '3000:5173'
    env_file:
      - .env.test
    volumes:
      - ./:/app
      - /app/node_modules/
    working_dir: /app
    command: sh -c "pnpm install && pnpm run db:deploy && pnpm run s3devdata && pnpm run seed && pnpm run dev --host --port 5173"
    depends_on:
      - db
